### ISSUE TITLE
Closing client hangs when response content stream is not consumed

### ISSUE THREAD

**Issue by jarlah** [octeep/idris2-http#7]
ref https://github.com/jarlah/idris2-http-client-usage

idris2-http seems to be very slow or im doing something wrong.

Sometimes it completes with 

(200 ** OK)
"Done"

Most often it hangs aftger (200 ** OK)

Other times it just hangs with no output.

Why is that?

```haskell
module Main

import Network.HTTP
import Network.HTTP.URL
import Data.Nat 
import Control.Monad.Error.Either
import Control.Monad.Error.Interface

ResultMonad : Type -> Type
ResultMonad = EitherT (HttpError ()) IO

getClient: IO (HttpClient ())
getClient = new_client_default

performRequest : HttpClient () -> ResultMonad (HttpResponse, Stream (Of Bits8) ResultMonad ())
performRequest client = 
  request client GET (url' "http://openbsd.org/70.html") [] ()
 
main : IO ()
main = do
    client <- getClient
    result <- runEitherT $ performRequest client
    case result of
      Left err => printLn err
      Right (response, stream) =>
        printLn (status_code response)
    close client
    printLn "Done"

```

**Comment by ReilySiegel** [comment]
I've taken a quick look at this. It appears that the hanging is caused by not consuming the content stream. Changing your `main` to 

```idris
main : IO ()
main = do
    client <- getClient
    
    Right (result, stream) <- runEitherT $ performRequest client
      | Left e => printLn "Error"
    Right (content, _) <- runEitherT $ toList stream
      | Left e => printLn "Error"    

    printLn (status_code result)
    close client
    printLn "Done"
```
results in consistent termination. This should probably be enforced by types, but given below, I'm not convinced that fixing that is a productive use of time.

As for the slowness, I am not familiar enough with the way the library works to properly debug/optimize, but it looks like a majority of the time measured (on my laptop) is CPU time, and a significant part of that is just creating the client (2.7 seconds on my machine!!). I think the optimal way to move forward is to work on a library wrapping libcurl (or similar), and presenting a convenient non-blocking interface using stefan-hoeck/idris2-async. This is something that ill probably work on *eventually* but it involves a lot of learning for me. My background is in clojure, so complex type systems and low level IO are both foreign to me. If you'd like to work on optimizing this library, though, I'd be more than happy to review. I'm sure there's a ton of low-hanging fruit.

**Comment by jarlah** [comment]
thanks for the reply :)

**Comment by ReilySiegel** [comment]
Feel free to open a tracking issue for optimization if that is helpful for you.
